---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: localhost
  ansible_connection: ssh
  ansible_sudo: false
  ansible_verbose: true
  ansible_verbosity: 3
  require_chef_for_busser: false
  enable_yum_epel: true

platforms:
  - name: centos-7
    driver_config:
      privileged: true
      run_command: /sbin/init; sleep 10
  - name: amazonlinux-2017.03
    driver_config:
      image: amazonlinux:2017.03
      platform: centos

verifier:
  name: serverspec
  env_vars:
    TARGET_HOST: localhost
    LOGIN_USER: kitchen
    SSH_KEY: 'roles/ansible-role-elasticsearch/.kitchen/docker_id_rsa'

suites:
  - name: default
    verifier:
      patterns:
        - roles/ansible-role-elasticsearch/test/integration/default/serverspec/*_spec.rb
