---

- set_fact:
    rpm_url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{elasticsearch_version}}.rpm

- name: install elasticsearch
  yum:
    name: "{{rpm_url}}"
    state: present
